import torch
import torch.nn.functional as F
import os
from autocomplete import initialize_model
from tokenization import Tokenizer, strip_generated_ids
from torch.nn.utils.rnn import pad_sequence
import numpy as np
import sys


def get_predictions(
    logits, prediction_threshold, mode, temperature=1, id_for_incorrect=-1
):
    if mode == "top_pred":
        probs = F.softmax(logits / temperature, dim=-1)  # converting each logit to %s
        probs, preds = torch.max(
            probs, dim=-1
        )  # one matrix for the each char prediction and another matrix for "confidence" of each prediction
        preds = torch.where(
            probs >= prediction_threshold, preds, torch.tensor(id_for_incorrect)
        )  # (B,T)
        # Compare all of probs to all of threshold. If the prediction is sufficiently confident, the prediction is used for the element. Otherwise, id_for_unknown used
        return preds
    else:
        probs = F.softmax(logits / temperature, dim=-1)  # converting each logit to %s
        top_probs, top_preds = torch.topk(
            probs, k=2, dim=-1
        )  # # one matrix for top 2 char predictions and another matrix for "confidence" of these predictions

        top_guess_confidence = top_probs[:, :, 0]  # all probs of top guess
        second_guess_confidence = top_probs[:, :, 1]  # all probs of second guess
        top_guess = top_preds[:, :, 0]  # the actual top guesses

        margin = (
            top_guess_confidence - second_guess_confidence
        )  # gap between 1st and 2nd guesses
        preds = torch.where(
            margin >= prediction_threshold, top_guess, torch.tensor(id_for_incorrect)
        )
        # If the prediction is sufficiently confident, the prediction is used for the element. Otherwise, id_for_unknown used
        return preds


class AutocompletingTokenizer(Tokenizer):
    def __init__(
        self,
        model,
        device,
        max_length=None,
        max_length_encoding=1,
        keep_first=False,
        keep_eos=False,
    ):
        self.model = model.to(device)
        self.device = device
        self.max_length_encoding = max_length_encoding
        # Target-side use: never remove the first byte or the EOS. An EOS that is
        # removed can't be generated by a decoder, and a removed first byte would
        # leave the leading run's length with nowhere to be recorded.
        self.keep_first = keep_first
        self.keep_eos = keep_eos
        self.special_tokens = {"<pad>": 0, "lang_Lang": 1, "</s>": 2}
        self.max_length = max_length
        self.prediction_threshold = 0.8
        self.prediction_mode = "top_pred"
        self.tokens_processed = 0
        self.tokens_outputted = 0
        self.sents_processed = 0
        self.omitted = dict()
        self.total = dict()

    def __call__(self, sent: str, lang_code="lang_Lang"):
        input_ids = [self.special_tokens[lang_code]] + [
            byte + len(self.special_tokens) for byte in sent.encode()
        ]
        self.sents_processed += 1

        if self.sents_processed % 1000000 == 0:
            print(
                f"COMPRESSION RATIO: {self.tokens_outputted / self.tokens_processed: .3f}"
            )
            sys.stdout.flush()

        self.tokens_processed += len(input_ids)
        target_ids = [byte + len(self.special_tokens) for byte in sent.encode()] + [
            self.special_tokens["</s>"]
        ]

        input_ids = torch.tensor(input_ids).unsqueeze(0).to(self.device)
        target_ids = torch.tensor(target_ids).unsqueeze(0).to(self.device)
        logits = self.model(input_ids)  # (B, T, vocab_size)
        preds = get_predictions(
            logits,
            self.prediction_threshold,
            mode=self.prediction_mode,
            temperature=1,
            id_for_incorrect=-1,
        ).reshape(-1)
        input_ids = input_ids.reshape(-1)
        target_ids = target_ids.reshape(-1)
        target_ids = target_ids[:1024]  # TODO: make more robust
        correct = preds == target_ids
        if self.keep_first:
            correct[0] = False
        if self.keep_eos and len(sent.encode()) < 1024:
            correct[-1] = False
        tokens = []
        correct_accumulator = 0

        for j in range(len(correct) - 1, -1, -1):
            if correct[j]:
                correct_accumulator += 1
            else:
                offset = 256 * min(correct_accumulator, self.max_length_encoding)
                tokens.append(target_ids[j].item() + offset)
                correct_accumulator = 0
        tokens.append(input_ids[0].item())
        tokens.reverse()

        self.tokens_outputted += len(tokens)
        if self.max_length is not None and len(tokens) > self.max_length - 1:
            tokens = tokens[: self.max_length - 1] + [self.special_tokens["</s>"]]

        return tokens

    def __len__(self):
        return 256 + len(self.special_tokens) + (256 * self.max_length_encoding)

    def get_special_tokens(self):
        return self.special_tokens

    @torch.no_grad()
    def compress_runs(self, sents, max_tokens_per_forward=32768):
        """Batched compression that keeps the uncapped run lengths.

        Returns, for each sentence, (base, run): base[i] is the id (2..258) of the
        i-th kept token (EOS included when kept), run[i] the number of removed bytes
        that follow it (clipped to 255). The language token is not included. Any cap
        can then be applied afterwards as base + 256 * min(run, cap), so a single pass
        over a corpus serves every cap. Sentences are sorted by length and packed so
        each forward pass sees at most max_tokens_per_forward positions.
        """
        self.model.eval()
        data = [s.encode() for s in sents]
        if any(len(b) >= 1024 for b in data):
            raise ValueError("compress_runs needs sentences shorter than 1024 bytes")
        order = sorted(range(len(data)), key=lambda i: len(data[i]))
        results = [None] * len(data)
        start = 0
        while start < len(order):
            end = start + 1
            while end < len(order) and (end + 1 - start) * (
                len(data[order[end]]) + 1
            ) <= max_tokens_per_forward:
                end += 1
            chunk = order[start:end]
            start = end
            lens = [len(data[i]) for i in chunk]
            B, T = len(chunk), max(lens) + 1
            inp = torch.zeros(B, T, dtype=torch.long)
            tgt = torch.full((B, T), -1, dtype=torch.long)
            for row, i in enumerate(chunk):
                ids = torch.tensor(list(data[i])) + 3
                inp[row, 0] = self.special_tokens["lang_Lang"]
                inp[row, 1 : lens[row] + 1] = ids
                tgt[row, : lens[row]] = ids
                tgt[row, lens[row]] = self.special_tokens["</s>"]
            inp, tgt = inp.to(self.device), tgt.to(self.device)
            valid = tgt >= 0
            preds = get_predictions(
                self.model(inp),
                self.prediction_threshold,
                mode=self.prediction_mode,
                temperature=1,
                id_for_incorrect=-1,
            )
            correct = (preds == tgt) & valid
            if self.keep_first:
                correct[:, 0] = False
            if self.keep_eos:
                correct[torch.arange(B, device=self.device), torch.tensor(lens, device=self.device)] = False
            # f[j] = number of consecutive removed positions starting at j
            rev = correct.flip(1).long()
            csum = rev.cumsum(1)
            f = (csum - torch.where(rev == 0, csum, 0).cummax(1).values).flip(1)
            run_after = torch.cat([f[:, 1:], torch.zeros_like(f[:, :1])], dim=1)
            kept = (valid & ~correct).cpu().numpy()
            tgt_np = tgt.cpu().numpy()
            run_np = run_after.clamp(max=255).cpu().numpy()
            for row, i in enumerate(chunk):
                mask = kept[row]
                results[i] = (
                    tgt_np[row][mask].astype(np.uint16),
                    run_np[row][mask].astype(np.uint8),
                )
        return results

    def compress_batch(self, sents, max_tokens_per_forward=32768):
        """Batched equivalent of calling the tokenizer on every sentence."""
        out = [None] * len(sents)
        short = [i for i, s in enumerate(sents) if len(s.encode()) < 1024]
        for i, s in enumerate(sents):
            if len(s.encode()) >= 1024:
                out[i] = self(s)  # rare: keep the per-sentence behaviour
        runs = self.compress_runs([sents[i] for i in short], max_tokens_per_forward)
        cap = self.max_length_encoding
        eos = self.special_tokens["</s>"]
        for i, (base, run) in zip(short, runs):
            tokens = [self.special_tokens["lang_Lang"]] + (
                base.astype(np.int64) + 256 * np.minimum(run.astype(np.int64), cap)
            ).tolist()
            self.sents_processed += 1
            self.tokens_processed += len(sents[i].encode()) + 1
            self.tokens_outputted += len(tokens)
            if self.max_length is not None and len(tokens) > self.max_length - 1:
                tokens = tokens[: self.max_length - 1] + [eos]
            out[i] = tokens
        return out

    @torch.no_grad()
    def decompress(self, kept_lists, max_out=1000):
        """Greedy autocomplete fill-in of compressed id sequences.

        kept_lists: one list of compressed ids per sentence, without the language
        token; an explicit EOS (2) ends a sentence. A kept byte with marker k is
        followed by k bytes filled in with the autocomplete model's top guess. A
        marker equal to the cap only says "at least k", so the run then continues
        for as long as the model stays confident. Returns one bytes object per
        sentence. Exact for valid sequences (see test_target_side.py).
        """
        self.model.eval()
        n = len(kept_lists)
        cap = self.max_length_encoding
        prefix = [[self.special_tokens["lang_Lang"]] for _ in range(n)]
        out = [[] for _ in range(n)]
        pos, need = [0] * n, [0] * n
        saturated, done = [False] * n, [False] * n
        eos = self.special_tokens["</s>"]

        def emit(i, token):
            prefix[i].append(token)
            out[i].append(token)
            if token == eos or len(prefix[i]) >= max_out:
                done[i] = True

        while not all(done):
            for i in range(n):  # sentences that need their next kept token
                if done[i] or need[i] > 0 or saturated[i]:
                    continue
                if pos[i] >= len(kept_lists[i]):
                    done[i] = True
                    continue
                t = kept_lists[i][pos[i]]
                pos[i] += 1
                if t == eos:
                    emit(i, eos)
                    continue
                k, b = divmod(t - 3, 256)
                emit(i, b + 3)
                need[i] = min(k, cap)
                saturated[i] = k >= cap
            idx = [i for i in range(n) if not done[i] and (need[i] > 0 or saturated[i])]
            if not idx:
                continue
            batch = pad_sequence(
                [torch.tensor(prefix[i]) for i in idx],
                batch_first=True,
                padding_value=0,
            ).to(self.device)
            # Only the position after each prefix matters; pick it out before the softmax
            # and bring the results to the host once per step, not once per row.
            rows = torch.arange(len(idx), device=batch.device)
            last = torch.tensor([len(prefix[i]) - 1 for i in idx], device=batch.device)
            logits = self.model(batch)[rows, last]
            conf, guess = F.softmax(logits, dim=-1).max(dim=-1)
            conf, guess = conf.tolist(), guess.tolist()
            for row, i in enumerate(idx):
                if need[i] > 0:
                    emit(i, guess[row])
                    need[i] -= 1
                elif conf[row] >= self.prediction_threshold:
                    emit(i, guess[row])  # saturated run keeps going
                else:
                    saturated[i] = False
        return [bytes(t - 3 for t in o if t >= 3) for o in out]

    def batch_decode(self, token_ids):
        kept = [strip_generated_ids(row) for row in token_ids]
        return [
            data.decode("utf-8", errors="replace") for data in self.decompress(kept)
        ]


def load_autocompleting_tokenizer(
    model_dir, max_length, max_length_encoding, keep_first=False, keep_eos=False
):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = initialize_model(max_length=1024)
    checkpoint = torch.load(
        os.path.join(model_dir, "best_model.pt"), map_location="cpu"
    )
    model.load_state_dict(checkpoint["model_state_dict"])
    model.to(device)
    model.eval()
    return AutocompletingTokenizer(
        model,
        device,
        max_length=max_length,
        max_length_encoding=max_length_encoding,
        keep_first=keep_first,
        keep_eos=keep_eos,
    )


if __name__ == "__main__":

    max_length = 192
    model_dir = "experiments/autocomplete-v1"

    tokenizer = load_autocompleting_tokenizer(model_dir, max_length)
    with open("test_files/lang1.txt") as reader:
        lines = [line.strip() for line in reader.readlines()]

    numerator, denominator = 0, 0
    for line in lines:
        tokens = tokenizer(line, lang_code="eng_Latn")
        numerator += len(tokens)
        denominator += len(line) + 2
        # for tok in tokens:
        #     if tok == 1:
        #         print("eng_Latn")
        #     elif tok == 2:
        #         print("</s>")
        #     elif 3 <= tok <= 3 + 256:
        #         print(chr(tok - 3) + "*")
        #     else:
        #         print(chr(tok - 259))
    print(numerator / denominator)
